site_name: Tecnicologia

docs_dir: ../docs

theme:
  name: material
  logo: https://raw.githubusercontent.com/csiglab/Meta/refs/heads/main/img/o/png/bremontix-laboratorio-tecnicologia_512x512.png
  favicon: favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# nav:
#   - Home: docs/Meta/README.md  # This will now be served at /
#   - About: docs/Meta/Guia-Mayor.md
    #  - Research: research.html

extra_javascript:
  # - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  # - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  # - js/math.js  # We'll create this
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css